name: Android CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  prepare:
    uses: ./.github/workflows/setup-environment.yml
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'github/module-graph' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "SDK_DIR=${{ secrets.SDK_DIR }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build