name: Detekt Static Code Analysis

on:
  pull_request:
    branches: [ "master" ]

jobs:
  prepare:
    uses: ./.github/workflows/setup-environment.yml
  detekt:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref != 'github/module-graph' }}
    steps:
      - uses: actions/checkout@v3

      - name: Run Detekt and generate reports
        run: |
          chmod +x gradlew
          ./gradlew detekt -Pconfig-file=path/to/your/detekt.yml -Poutput-format=xml,html -Poutput-dir=path/to/your/reports

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v3
        with:
          name: detekt-reports
          path: |
            path/to/your/reports/*.xml
            path/to/your/reports/*.html
