name: Generate Module Graphs and Commit

on:
  pull_request:
    branches: [ "github/module-graph" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Module Graphs
        run: |
          chmod +x ./generateModuleGraphs.sh
          ./generateModuleGraphs.sh

      - name: Commit and Push Changes to github/module-graph
        run: |
          git config --global user.email "github@actions.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI generated updates" || echo "No changes to commit"
          git push --set-upstream https://${{ secrets.PERSONAL_TOKEN }}@github.com/ubuntuyiw/MultiModReelCompose.git github/module-graph
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}