name: Generate Module Graphs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate-graphs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Module Graphs
        run: |
          chmod +x ./generateModuleGraphs.sh
          ./generateModuleGraphs.sh

      - name: Upload Graphs
        uses: actions/upload-artifact@v3
        with:
          name: module-graphs
          path: docs/images/graphs/