name: Generate Module Graphs and Commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Module Graphs
        run: |
          chmod +x ./generateModuleGraphs.sh
          ./generateModuleGraphs.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.email "githubt@actions.com"
          git config --global user.name "Github"
          git add docs/images/graphs/
          git add **/README.md
          git commit -m "Update module graphs and READMEs" || echo "No changes to commit"
          git push

      - name: Upload Graphs
        uses: actions/upload-artifact@v3
        with:
          name: module-graphs
          path: docs/images/graphs/