name: Setup Java Environment

on:
  workflow_call:

jobs:
  setup-java:
    runs-on: ubuntu-latest
    outputs:
      java-home: ${{ steps.set-java.outputs.java-home }}
    steps:
      - name: Set up JDK 17
        id: set-java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle